version: '3.9'
services:
  api_backend:
    build: .
    container_name: api
    command: 'npm start'
    environment:
      - PORT=1234
      - MONGO_USER=root
      - MONGO_PASSWORD=example
    ports:
      - 8080:1234
    volumes:
      - .:/app
      - /app/node_modules

# Run standalone mongo 
    # depends_on:
    #   - api_db

  # api_db:
  #   image: mongo
  #   container_name: api_db
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   volumes:
  #     - mongo-db:/data/db

# volumes:
#   mongo-db: