version: '3.9'
services:
  api_backend:
    build: .
    container_name: api
    networks:
      - trysts
    command: 'npm start'
    environment:
      - PORT=8080
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - MONGO_IP=api_db
      - MONGO_PORT=27017
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - api_db

  api_db:
    image: mongo
    container_name: api_db
    networks:
      - trysts
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-db:/data/db

networks:
  trysts:
    driver: bridge

volumes:
  mongo-db: